Version 1.4.0
aivancioglo/RestTest pull request #10
Opened 2018-05-31 14:41 UTC by aivancioglo

2018-08-22 08:43 UTC, dlenroc approved these changes

2018-08-22 09:52 UTC, stia-na requested changes

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Repeater.kt
> +     * This function is executing your request until passing or timeout.
Please rename to "This function will execute your request until it returns expected result. If the expected result was not met, it will timeout if timeout was set."

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Request.kt
>       * @param setters are setting up request specification.
Please change to `@param setters Setters are setting up request specification.`

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
>   * This class is using for HTTP/HTTPS response validation and processing.
Please change "This class is used for HTTP/HTTPS response validation and processing."

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * Making response validation.
Performing response validation?

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param verifiers for response validation.
@param verifiers Verifiers for response validation.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * Making response validation.
Performing response validation.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param verifiers for response validation.
@param verifiers Verifiers for response validation.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * Making response validation.
Performing response validation?

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param code of response.
@param code Status code of response.

You can say that it is integer or numeric.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param verifiers for response validation.
@param verifiers Verifiers for response validation.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * Making response validation.
Performing response validation

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param verifiers for response validation.
@param statusCode Status code of response.
@param verifiers Verifiers for response validation.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * Making response validation.
Performing

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param statusCodes of response.
@param statusCodes Status codes of response.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param verifiers for response validation.
@param verifiers Verifiers for response validation.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * Making response validation.
Performing

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param verifiers for response validation.
@param code Status code of response.
@param schema Schema for response validation.
@param verifiers Verifiers for response validation.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * Making response validation.
Performing

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param statusCode of response.
@param statusCode Status code of response.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param verifiers for response validation.
@param verifiers Verifiers for response validation.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * Making response validation.
Performing

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param statusCodes of response.
@param statusCodes Status codes of response.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param verifiers for response validation.
@param verifiers Verifiers for response validation.

2018-08-22 09:52 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * Set root path.
You are following the "Making" word everywhere and not it is "Set", "Add". Please make it follow one style.

2018-10-24 12:58 UTC, stia-na approved these changes

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * Returns Rest Assured response.
Returns validatable response.

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * For getting response code of last then.
For getting response code of last request returned by then().

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
>       * @param cls that of your module.
@param cls Class that will be deserialized.

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param T is response model.
@param T The response model.

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param cls that of your module.
@param cls Class that will be deserialized.

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param T is response model.
@param T The response model.

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @return deserialize body as your model class.
deserialized

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * Deserialize response body as your model class.
deserialize

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
>       * @param cls that of your module.
@param cls Class that will be deserialized.

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param T is response model.
@param T The response model.

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
>       * @param objectMapper for response body deserializing.
@param objectMapper Object mapper for response body deserialization.

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param cls that of your module.
@param cls Class that will be deserialized.

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param objectMapper for response body deserializing.
@param objectMapper Object mapper for response body deserialization.

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @param T is response model.
@param T The response model.

2018-10-24 12:58 UTC, stia-na commented on src/main/kotlin/com/github/aivancioglo/resttest/http/Response.kt
> +     * @return deserialize body as your model class.
deserialized

2018-10-24 13:13 UTC, stia-na approved these changes

2018-10-24 13:19 UTC, merged